# Manual publication entries
# Add your own publications here with custom metadata, images, buttons, etc.
# Example format:
# - id: doi:10.1234/example
#   image: https://example.com/image.jpg
#   tags:
#     - tag1
#     - tag2

[]
