# Manual publication entries
# Add your own publications here with custom metadata, images, buttons, etc.
# Example format:
# - id: doi:10.1234/example
#   image: https://example.com/image.jpg
#   tags:
#     - tag1
#     - tag2

# PhD Thesis - manual image URL since EPFL no longer provides OpenGraph tags
- id: doi:10.5075/epfl-thesis-8139
  image: https://infoscience.epfl.ch/bitstreams/ba65466f-2aeb-415d-86ef-285f53482e9b/download

# Featured publications with custom highlight images
- id: arxiv:2511.01966
  image: images/publications_highlights/asymmetry.png
  description: >
    We consider the entanglement asymmetry as a symmetry probe in gauge theories.
    We compute it analytically in the massless Schwinger model and show it to be
    parametrically more sensitive to symmetry breaking/restoration than the
    corresponding local order parameter for the chiral symmetry.

- id: doi:10.1103/sgrx-jpp9
  image: images/publications_highlights/thermalization_quantum_entanglement.png
  description: >
    This work demonstrates how quantum entanglement drives thermalization in
    jet-like excitations within the massive Schwinger model. Using tensor
    network simulations of real-time evolution, we show that entanglement
    generation provides a microscopic mechanism for thermalization in this strongly
    interacting gauge theory.

- id: doi:10.1103/PhysRevD.109.L071501
  image: images/publications_highlights/negativitynew3.png
  description: >
    We establish that the two-fermion negativity, a particular measure of
    multipartite entanglement, detects confinement in the massive Schwinger model.
    This reinforces the intuition that quantum correlations are sensitive to the
    confinement/deconfinement transition.

- id: doi:10.21468/SciPostPhys.17.3.085
  image: images/publications_highlights/higher_forms.png
  description: >
    Higher-form symmetries can be used to constrain the long-range dynamics of
    interacting systems. Magneto-hydrodynamics can be derived from the conservation
    of magnetic lines and chiral transport emerges from the presence of a non-invertible
    symmetry. We demonstrate the practicality of these ideas in classical-statistical
    simulations, where we compute the predicted transports from first principles.
